const bank_name= [
    "State Bank of India (SBI)",
    "Punjab National Bank (PNB)",
    "Bank of Baroda (BOB)",
    "Allahabad Bank",
    "Union Bank of India",
    "Canara Bank",
    "Indian Bank",
    "HDFC Bank",
    "ICICI Bank",
    "Axis Bank",
    "Kotak Mahindra Bank",
    "Yes Bank",
    "IDBI Bank",
    "Bank of India (BOI)",
    "Central Bank of India",
    "UCO Bank",
    "Corporation Bank",
    "Andhra Bank",
    "Vijaya Bank",
    "Oriental Bank of Commerce (OBC)",
    "Dena Bank",
    "Syndicate Bank",
    "Karnataka Bank",
    "Karur Vysya Bank",
    "Federal Bank",
    "IndusInd Bank",
    "South Indian Bank",
    "Catholic Syrian Bank",
    "The Nainital Bank",
    "Bandhan Bank",
];

module.exports = bank_name;