# Generated by Django 4.1.11 on 2023-10-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_remove_userprofile_user_id_userprofile_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='public_id',
            field=models.CharField(max_length=20),
        ),
    ]
