# Generated by Django 4.1.11 on 2023-10-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_userprofile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='public_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
